name: MERN CD

on:
  workflow_run:
    workflows: ["MERN CI"] # Name of your CI workflow
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          script: | 
           cd devops-mern-todo/ 
           git pull origin main
           docker-compose down
           docker-compose up --build -d